# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-29 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogspost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='category',
            field=models.CharField(default='python', max_length=150),
            preserve_default=False,
        ),
    ]
